#!/bin/sh

# disable filename globbing
set -f

echo Content-type: text/plain
echo

echo CGI/1.0 test script report:
echo

echo argc is $#. argv is "$*".
echo

echo setenv SERVER_SOFTWARE "\"$SERVER_SOFTWARE\""
echo setenv SERVER_NAME "\"$SERVER_NAME\""
echo setenv GATEWAY_INTERFACE "\"$GATEWAY_INTERFACE\""
echo setenv SERVER_PROTOCOL "\"$SERVER_PROTOCOL\""
echo setenv SERVER_PORT "\"$SERVER_PORT\""
echo setenv REQUEST_METHOD "\"$REQUEST_METHOD\""
echo setenv HTTP_ACCEPT "\"$HTTP_ACCEPT\""
echo setenv PATH_INFO "\"$PATH_INFO\""
echo setenv PATH_TRANSLATED "\"$PATH_TRANSLATED\""
echo setenv SCRIPT_NAME "\"$SCRIPT_NAME\""
echo setenv QUERY_STRING "\"$QUERY_STRING\""
echo setenv REMOTE_HOST "\"$REMOTE_HOST\""
echo setenv REMOTE_ADDR "\"$REMOTE_ADDR\""
echo setenv REMOTE_USER "\"$REMOTE_USER\""
echo setenv AUTH_TYPE "\"$AUTH_TYPE\""
echo setenv CONTENT_TYPE "\"$CONTENT_TYPE\""
echo setenv CONTENT_LENGTH "\"$CONTENT_LENGTH\""
echo setenv HTTP_USER_AGENT "\"$HTTP_USER_AGENT\""
echo ""

read line
echo $line
echo ""
