<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * show the user the available data sorted by key
 *
 *  PHP version 4 and up
 *
 * LICENSE:
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @package	RBGMDB
 * @author 	José R. Valverde <jrvalverde@acm.org>
 * @copyright 	José R. Valverde <jrvalverde@acm.org>
 * @license	c/lgpl.txt
 * @version	$Id$
 * @link	http://www.es.embnet.org/Services/MolBio/rbgmdb/
 * @see		utils.php config.inc mysql_report.php
 * @since	File available since Release 1.0
 */
    
/**
 * include fPDF tools
 */
include('mysql_report.php');
/**
 * include DBMS credentials
 */
include 'config.inc';
/**
 * include utility functions
 */
include 'utils.php';



/**
 *  Generate a PDF report out of a user query
 *
 *  This function will connect to the specified database manager system using the ID
 *  and password provided, open the database (which we should have access to), run the
 *  user supplied query and generate a PDF report sorted according to user criteria.
 *
 *  The report will be returned directly to the user with the appropriate MIME type
 *  generated by the auxiliary library fPDF.
 *
 * @param string $db_host  	the DBMS host
 * @param string $db_user   	the user to connect to the DBMS as (should have access to the
 *  	    	    	    	database
 * @param string $db_password	the user's password to gaina access to the DBMS
 * @param string $db_name   	the name of the database
 * @param array  $request   	an associative array containing the query fields, keys and
 *  	    	    	    	boolean algebra combinations
 * @param string $how   	how to sort the resulting output
 */
function db_complex_query_pdf($db_host, $db_user, $db_password, $db_name, $request, $how)
{
    // Set up a query to show what we were requested
    $query = "SELECT * FROM mut_nt";
    
    $first_cond = 0;
    foreach ($request as $cond) {
    	// check if this condition states something to search
    	if (($cond['fld'] != "") && ($cond['qry'] != "")) {
	    // first valid condition is special
	    if ($first_cond == 0) {
		$first_cond = 1;
	    	$query .= " WHERE ";
		if ($cond['op'] == "NOT")
		    // ignore AND and OR on the first valid condition
		    $query .= " {$cond['op']} ";
	    }
	    else
	    	$query .= " {$cond['op']} ";
	    
	    if ($cond['qry'] == "NULL")
	    	// NULL requires a special syntax
	        $query .= " {$cond['fld']} IS NULL ";
	    else
	        $query .= " {$cond['fld']} like '%{$cond['qry']}%'";
	}
    }
    if ($how != "")
    	$query .= " ORDER BY $how";


    // run the query
    $pdf = new PDF('L','pt','A3');
    $pdf->SetFont('Arial','',10);
    $pdf->AliasNbPages();
    $pdf->connect($db_host, $db_user, $db_password, $db_name);
    $attr=array('titleFontSize'=>18,'titleText'=> 'RBDB results sorted by \''.$how.'\'');
    $pdf->mysql_report($query, false, $attr);

    return;
}


// Here we go
$combine1 = escapeshellcmd($_GET["combine1"]);
$field1 = escapeshellcmd($_GET["field1"]);
$query1 = escapeshellcmd($_GET["query1"]);

$combine2 = escapeshellcmd($_GET["combine2"]);
$field2 = escapeshellcmd($_GET["field2"]);
$query2 = escapeshellcmd($_GET["query2"]);

$combine3 = escapeshellcmd($_GET["combine3"]);
$field3 = escapeshellcmd($_GET["field3"]);
$query3 = escapeshellcmd($_GET["query3"]);

$combine4 = escapeshellcmd($_GET["combine4"]);
$field4 = escapeshellcmd($_GET["field4"]);
$query4 = escapeshellcmd($_GET["query4"]);

// bundle all together
//	might be done directly (in-line call), but would be less evident.
$q = array(
	array('op' => $combine1, 'fld' => $field1, 'qry' => $query1),
	array('op' => $combine2, 'fld' => $field2, 'qry' => $query2),
	array('op' => $combine3, 'fld' => $field3, 'qry' => $query3),
	array('op' => $combine4, 'fld' => $field4, 'qry' => $query4)
);

$sort  = escapeshellcmd($_GET["sort"]);


// show all
db_complex_query_pdf($db_host, $db_user, $db_password, $db_name, $q, $sort);

?>
